model:
    arch: maskrcnn_res50_ssnvvh
data:
    img_rows: 128
    img_cols: 'same'
    path: /home/dell/lsq/Data
    test_path: /home/dell/lsq/Data/Test
    num_classes: 2
    n_maxdisp: 192
    area_thd: 4
    label_is_nos: False
    seasons_mode: 'intact'
    channels: 20
    if_buffer: True
    buffer_pixels: 1

training:
    shuffle: True
    lr: 0.0001
    nos_task: True
    epochs: 101
    batch_size: 8
    resume: ''
    device: 'cuda'
    check_val_every_n_epoch : 1
    max_epochs : 2000
    gt_rpn_training: True

test:
    resume: '/media/dell/xpl/lsq/CKPTS/SEASONet_RidofChanged/finetune_80.tar'
savepath: /media/shihaoze/lsq/62City/Results/SEASONet_RidofChanged_80